language: shell
services:
  - docker
jobs:
  include:
    - stage: build & push core Docker image
      script:
        - 'docker -D build -f .devcontainer/Dockerfile --tag antojf/$(basename -- $TRAVIS_BUILD_DIR):latest .'
        - bash docker_push $(basename -- $TRAVIS_BUILD_DIR)